# Generated by Django 6.0.5 on 2026-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scan_type',
            field=models.CharField(max_length=100),
        ),
    ]
