# Generated by Django 6.0.5 on 2026-05-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_category', models.CharField(choices=[('X-Ray', 'X-Ray'), ('Ultrasound', 'Ultrasound')], max_length=50)),
                ('scan_image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('clinical_notes', models.TextField(blank=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
